/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class LinearSearch extends javax.swing.JFrame {
ArrayList<JTextField> T=new ArrayList(10);
int n;
int key,m;
int low,high;
    /**
     * Creates new form LinearSearch
     */
    public LinearSearch() {
        initComponents();N.setEditable(true);
        k.setEditable(true);
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        T.add(T1);T.add(T2);T.add(T3);T.add(T4);T.add(T5);T.add(T6);T.add(T7);T.add(T8);T.add(T9);T.add(T10);
        for(int i=0;i<10;i++)
            T.get(i).setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        N = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        rslt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(154, 209, 212));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 50, 73));
        jLabel1.setText("Binary Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 20, 180, 33);

        T1.setBackground(new java.awt.Color(154, 209, 212));
        T1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T1.setForeground(new java.awt.Color(0, 50, 73));
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T1);
        T1.setBounds(250, 110, 40, 40);

        T2.setBackground(new java.awt.Color(154, 209, 212));
        T2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T2.setForeground(new java.awt.Color(0, 50, 73));
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T2);
        T2.setBounds(310, 110, 40, 40);

        T3.setBackground(new java.awt.Color(154, 209, 212));
        T3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T3.setForeground(new java.awt.Color(0, 50, 73));
        T3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T3);
        T3.setBounds(370, 110, 40, 40);

        T4.setBackground(new java.awt.Color(154, 209, 212));
        T4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T4.setForeground(new java.awt.Color(0, 50, 73));
        T4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T4);
        T4.setBounds(430, 110, 40, 40);

        T5.setBackground(new java.awt.Color(154, 209, 212));
        T5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T5.setForeground(new java.awt.Color(0, 50, 73));
        T5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T5);
        T5.setBounds(490, 110, 40, 40);

        T6.setBackground(new java.awt.Color(154, 209, 212));
        T6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T6.setForeground(new java.awt.Color(0, 50, 73));
        T6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T6);
        T6.setBounds(550, 110, 40, 40);

        T7.setBackground(new java.awt.Color(154, 209, 212));
        T7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T7.setForeground(new java.awt.Color(0, 50, 72));
        T7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T7);
        T7.setBounds(610, 110, 40, 40);

        T8.setBackground(new java.awt.Color(154, 209, 212));
        T8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T8.setForeground(new java.awt.Color(0, 50, 73));
        T8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T8);
        T8.setBounds(670, 110, 40, 40);

        T9.setBackground(new java.awt.Color(154, 209, 212));
        T9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T9.setForeground(new java.awt.Color(0, 50, 73));
        T9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jPanel1.add(T9);
        T9.setBounds(730, 110, 40, 40);

        T10.setBackground(new java.awt.Color(109, 195, 204));
        T10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T10.setForeground(new java.awt.Color(0, 125, 152));
        T10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T10.setText("0");
        T10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(T10);
        T10.setBounds(955, 187, 42, 38);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 50, 73));
        jLabel2.setText("Location:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 450, 80, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 50, 73));
        jLabel3.setText("Enter the number of elements (<10) :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 220, 290, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 50, 73));
        jLabel4.setText("Click on \"Load\" once you have entered all the elements");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 290, 440, 30);

        loc.setEditable(false);
        loc.setBackground(new java.awt.Color(154, 209, 212));
        loc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loc.setForeground(new java.awt.Color(0, 50, 73));
        loc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(loc);
        loc.setBounds(650, 440, 60, 30);

        N.setBackground(new java.awt.Color(154, 209, 212));
        N.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        N.setForeground(new java.awt.Color(0, 50, 73));
        N.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 50, 73)));
        jPanel1.add(N);
        N.setBounds(650, 220, 60, 30);

        jButton1.setBackground(new java.awt.Color(128, 206, 215));
        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 50, 73));
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 520, 150, 60);

        jButton2.setBackground(new java.awt.Color(128, 206, 215));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 50, 73));
        jButton2.setText("Enter");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 200, 110, 50);

        jButton3.setBackground(new java.awt.Color(128, 206, 215));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 50, 73));
        jButton3.setText("Load");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(750, 280, 110, 50);

        jButton4.setBackground(new java.awt.Color(128, 206, 215));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 50, 73));
        jButton4.setText("Ok");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(760, 350, 80, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 50, 73));
        jLabel5.setText("Enter the number to search:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 340, 220, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 50, 73));
        jLabel6.setText("Result:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(560, 390, 60, 30);

        k.setBackground(new java.awt.Color(154, 209, 212));
        k.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        k.setForeground(new java.awt.Color(0, 125, 152));
        k.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        k.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 50, 73)));
        jPanel1.add(k);
        k.setBounds(650, 340, 60, 30);

        rslt.setEditable(false);
        rslt.setBackground(new java.awt.Color(154, 209, 212));
        rslt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rslt.setForeground(new java.awt.Color(0, 50, 73));
        rslt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rslt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 50, 73)));
        jPanel1.add(rslt);
        rslt.setBounds(650, 390, 160, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Untitled design (27).png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 360, 300, 250);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-macos-close-24.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(920, 0, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-about-30.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 20, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-go-back-48.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 530, 50, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-reset-48.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 530, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
n=Integer.parseInt(N.getText());
if(n>10)
{
    JOptionPane.showMessageDialog(null,"Please enter a number less than 10!");
    N.setText("");
}
else
{low=0;high=n-1;
for(int i=0;i<n;i++)
{
    T.get(i).setBackground(Color.white);
T.get(i).setEditable(true);
}
    JOptionPane.showMessageDialog(null,"Enter the elements:");
    N.setEditable(false);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        T.add(T1);T.add(T2);T.add(T3);T.add(T4);T.add(T5);T.add(T6);T.add(T7);T.add(T8);T.add(T9);T.add(T10);
for(int i=0;i<n-1;i++)
{
    if(Integer.parseInt(T.get(i).getText())  > Integer.parseInt(T.get(i+1).getText()))
    {
        JOptionPane.showMessageDialog(null,"Please enter the numbers in sorted order!");
        for(int j=0;j<n;j++)
            T.get(j).setText("");
    }
   
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
key=Integer.parseInt(k.getText());    
k.setEditable(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(low<high)
        {
        int mid=(low+high)/2;
       for(int i=0;i<n;i++)
           T.get(i).setBackground(Color.white);
        T.get(mid).setBackground(Color.gray);
        if(Integer.parseInt(T.get(mid).getText())==key)
        { JOptionPane.showMessageDialog(null,"Element found at location :"+(mid+1));
            jButton1.setEnabled(false);
            rslt.setText("FOUND");
            loc.setText(""+(mid+1));
        }
        else if(Integer.parseInt(T.get(mid).getText()) < key)
        {
            low=mid+1;
        }
        else
            high=mid-1;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Element not found");
            rslt.setText("NOT FOUND");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
aboutBS a=new aboutBS();
a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
LinearSearch l=new LinearSearch();
l.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinearSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinearSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinearSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinearSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinearSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField k;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField rslt;
    // End of variables declaration//GEN-END:variables
}
