/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class queueop extends javax.swing.JFrame {
ArrayList<JTextField> q=new ArrayList(10);
int L=-1,R=-1;
    /**
     * Creates new form queueop
     */
    public queueop() {
        initComponents();setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        q.add(T1);q.add(T2);q.add(T3);q.add(T4);q.add(T5);q.add(T6);q.add(T7);q.add(T8);q.add(T9);q.add(T10);
        for(int i=0;i<10;i++)
        {
            q.get(i).setEditable(false);
            q.get(i).setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(128, 206, 215));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 50, 73));
        jLabel1.setText("Queue");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(379, 19, 157, 45);

        T1.setEditable(false);
        T1.setBackground(new java.awt.Color(128, 206, 215));
        T1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T1.setForeground(new java.awt.Color(255, 255, 255));
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 0, 0)));
        T1.setMinimumSize(new java.awt.Dimension(40, 40));
        T1.setPreferredSize(new java.awt.Dimension(40, 40));
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        jPanel1.add(T1);
        T1.setBounds(300, 120, 40, 40);

        T2.setEditable(false);
        T2.setBackground(new java.awt.Color(128, 206, 215));
        T2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T2.setForeground(new java.awt.Color(255, 255, 255));
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T2.setMinimumSize(new java.awt.Dimension(40, 40));
        T2.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T2);
        T2.setBounds(340, 120, 40, 40);

        T3.setEditable(false);
        T3.setBackground(new java.awt.Color(128, 206, 215));
        T3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T3.setForeground(new java.awt.Color(255, 255, 255));
        T3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T3.setMinimumSize(new java.awt.Dimension(40, 40));
        T3.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T3);
        T3.setBounds(380, 120, 40, 40);

        T4.setEditable(false);
        T4.setBackground(new java.awt.Color(128, 206, 215));
        T4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T4.setForeground(new java.awt.Color(255, 255, 255));
        T4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T4.setMinimumSize(new java.awt.Dimension(40, 40));
        T4.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T4);
        T4.setBounds(420, 120, 40, 40);

        T5.setEditable(false);
        T5.setBackground(new java.awt.Color(128, 206, 215));
        T5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T5.setForeground(new java.awt.Color(255, 255, 255));
        T5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T5.setMinimumSize(new java.awt.Dimension(40, 40));
        T5.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T5);
        T5.setBounds(460, 120, 40, 40);

        T6.setEditable(false);
        T6.setBackground(new java.awt.Color(128, 206, 215));
        T6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T6.setForeground(new java.awt.Color(255, 255, 255));
        T6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T6.setMinimumSize(new java.awt.Dimension(40, 40));
        T6.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T6);
        T6.setBounds(500, 120, 40, 40);

        T7.setEditable(false);
        T7.setBackground(new java.awt.Color(128, 206, 215));
        T7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T7.setForeground(new java.awt.Color(255, 255, 255));
        T7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T7.setMinimumSize(new java.awt.Dimension(40, 40));
        T7.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T7);
        T7.setBounds(540, 120, 40, 40);

        T8.setEditable(false);
        T8.setBackground(new java.awt.Color(128, 206, 215));
        T8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T8.setForeground(new java.awt.Color(255, 255, 255));
        T8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T8.setMinimumSize(new java.awt.Dimension(40, 40));
        T8.setPreferredSize(new java.awt.Dimension(40, 40));
        T8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T8ActionPerformed(evt);
            }
        });
        jPanel1.add(T8);
        T8.setBounds(580, 120, 40, 40);

        T9.setEditable(false);
        T9.setBackground(new java.awt.Color(128, 206, 215));
        T9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T9.setForeground(new java.awt.Color(255, 255, 255));
        T9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T9.setMinimumSize(new java.awt.Dimension(40, 40));
        T9.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T9);
        T9.setBounds(620, 120, 40, 40);

        T10.setEditable(false);
        T10.setBackground(new java.awt.Color(128, 206, 215));
        T10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        T10.setForeground(new java.awt.Color(255, 255, 255));
        T10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 2, new java.awt.Color(0, 0, 0)));
        T10.setMinimumSize(new java.awt.Dimension(40, 40));
        T10.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(T10);
        T10.setBounds(660, 120, 40, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 50, 73));
        jLabel2.setText("Element dequeued:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 290, 150, 22);

        jButton1.setBackground(new java.awt.Color(128, 206, 215));
        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 50, 73));
        jButton1.setText("Queue");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(730, 200, 130, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 50, 73));
        jLabel3.setText("Enter the element to push into Queue:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 230, 300, 22);

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(630, 220, 0, 23);

        t.setEditable(false);
        t.setBackground(new java.awt.Color(128, 206, 215));
        t.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(t);
        t.setBounds(630, 280, 60, 30);

        d.setBackground(new java.awt.Color(128, 206, 215));
        d.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(d);
        d.setBounds(630, 220, 60, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-about-30.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 20, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-macos-close-24.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(920, 0, 30, 30);

        jButton3.setBackground(new java.awt.Color(128, 206, 215));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 50, 73));
        jButton3.setText("Dequeue");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(730, 280, 130, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-go-back-48.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 500, 50, 48);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-reset-48.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(550, 500, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/Untitled design (19).png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 250, 240, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if((R+1)>9)
    JOptionPane.showMessageDialog(null,"Queue is Full!");
else{
        if(L==-1 && R==-1)
{R=0;L=0;}
else
    R++;
       q.get(R).setText(d.getText());
      
        
}
d.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
t.setText("");
        if(R<L || L==-1)
{JOptionPane.showMessageDialog(null,"Queue is Empty!"); R=-1;L=-1;   }
else
{
    t.setText(q.get(L).getText());
    q.get(L).setText("");
    L++;
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
queueop o=new queueop();
o.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
aboutq s=new aboutq();
s.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void T8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(queueop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(queueop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(queueop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(queueop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new queueop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JTextField d;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
