/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication10;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.JTextField;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class treeop extends javax.swing.JFrame {
ArrayList<JTextField> po=new ArrayList(15);
ArrayList<JTextField> io=new ArrayList(15);
ArrayList<JTextField> pro=new ArrayList(15);
ArrayList<JTextField> T=new ArrayList(15);
BinaryTree tr=new BinaryTree();
Stack s=new Stack();
Stack t=new Stack();
Stack o=new Stack();
Stack ot=new Stack();
int i=0,n=0;

    void Inorder(Node node)
            
    {
        if(node==null)
                return;
        Inorder(node.left);
        s.push(node.key);
        for(int k=0;k<15;k++)
            if((""+node.key).equals(io.get(k).getText()))
                o.push(k);
        Inorder(node.right);        
        
    }
    void Postorder(Node node)
            
    {
        if(node==null)
                return;
        Postorder(node.left);
        Postorder(node.right); 
        s.push(node.key);
        for(int k=0;k<15;k++)
            if((""+node.key).equals(io.get(k).getText()))
                o.push(k);
               
        
    }
     void Preorder(Node node)
            
    {
        if(node==null)
                return;
       
        s.push(node.key);
        for(int k=0;k<15;k++)
            if((""+node.key).equals(io.get(k).getText()))
                o.push(k);
           Preorder(node.left);
        Preorder(node.right);      
        
    }
    /**
     * Creates new form treeop
     */
    public treeop() {
        initComponents();setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        jButton1.setEnabled(false);
jButton3.setEnabled(false);
jButton4.setEnabled(false);
        //POSTORDER
       
        po.add(RLLL);po.add(RLLR);po.add(RLL);po.add(RLRL);po.add(RLRR);po.add(RLR);po.add(RL);po.add(RRLL);po.add(RRLR);po.add(RRL);
        po.add(RRRL);po.add(RRRR);po.add(RRR);po.add(RR);po.add(R);
        
        //PREORDER
        
        pro.add(R);pro.add(RL);pro.add(RR);pro.add(RLL);pro.add(RLR);pro.add(RRL);pro.add(RRR);pro.add(RLLL);pro.add(RLLR);pro.add(RLRL);
        pro.add(RLRR);pro.add(RRLL);pro.add(RRLR);pro.add(RRRL);pro.add(RRRR);
        
        //INORDER
        
        io.add(RLLL);io.add(RLL);io.add(RLLR);io.add(RL);io.add(RLRL);io.add(RLR);io.add(RLRR);io.add(R);io.add(RRLL);io.add(RRL);
        io.add(RRLR);io.add(RR);io.add(RRRL);io.add(RRR);io.add(RRRR);
        
        //FOR T
        T.add(T1);T.add(T2);T.add(T3);T.add(T4);T.add(T5);T.add(T6);T.add(T7);T.add(T8);T.add(T9);T.add(T10);
        T.add(T11);T.add(T12);T.add(T13);T.add(T14);T.add(T15);
         for(int i=0;i<15;i++)
    io.get(i).setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RRRR = new javax.swing.JTextField();
        R = new javax.swing.JTextField();
        RL = new javax.swing.JTextField();
        RLL = new javax.swing.JTextField();
        RR = new javax.swing.JTextField();
        RLR = new javax.swing.JTextField();
        RRL = new javax.swing.JTextField();
        RRR = new javax.swing.JTextField();
        RLLL = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        RLLR = new javax.swing.JTextField();
        RLRL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RLRR = new javax.swing.JTextField();
        RRLR = new javax.swing.JTextField();
        RRLL = new javax.swing.JTextField();
        RRRL = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        T15 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        T10 = new javax.swing.JTextField();
        T11 = new javax.swing.JTextField();
        T12 = new javax.swing.JTextField();
        T13 = new javax.swing.JTextField();
        T14 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(154, 209, 212));
        jPanel1.setLayout(null);

        RRRR.setBackground(new java.awt.Color(0, 126, 167));
        RRRR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRRR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRRR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RRRR);
        RRRR.setBounds(570, 360, 40, 30);

        R.setBackground(new java.awt.Color(0, 126, 167));
        R.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        R.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(R);
        R.setBounds(290, 130, 40, 30);

        RL.setBackground(new java.awt.Color(0, 126, 167));
        RL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RL);
        RL.setBounds(130, 200, 30, 30);

        RLL.setBackground(new java.awt.Color(0, 126, 167));
        RLL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLL);
        RLL.setBounds(50, 280, 40, 30);

        RR.setBackground(new java.awt.Color(0, 126, 167));
        RR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RR);
        RR.setBounds(460, 200, 30, 30);

        RLR.setBackground(new java.awt.Color(0, 126, 167));
        RLR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLR);
        RLR.setBounds(210, 280, 30, 30);

        RRL.setBackground(new java.awt.Color(0, 126, 167));
        RRL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RRL);
        RRL.setBounds(370, 280, 40, 30);

        RRR.setBackground(new java.awt.Color(0, 126, 167));
        RRR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RRR);
        RRR.setBounds(540, 280, 40, 30);

        RLLL.setBackground(new java.awt.Color(0, 126, 167));
        RLLL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLLL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLLL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLLL);
        RLLL.setBounds(10, 360, 30, 30);

        jButton2.setBackground(new java.awt.Color(154, 209, 212));
        jButton2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 50, 73));
        jButton2.setText("Enter");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 520, 100, 50);

        RLLR.setBackground(new java.awt.Color(0, 126, 167));
        RLLR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLLR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLLR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLLR);
        RLLR.setBounds(90, 360, 40, 30);

        RLRL.setBackground(new java.awt.Color(0, 126, 167));
        RLRL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLRL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLRL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLRL);
        RLRL.setBounds(170, 360, 40, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-go-back-48.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 530, 60, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-reset-48.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(660, 520, 50, 48);

        RLRR.setBackground(new java.awt.Color(0, 126, 167));
        RLRR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RLRR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RLRR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RLRR);
        RLRR.setBounds(250, 360, 40, 30);

        RRLR.setBackground(new java.awt.Color(0, 126, 167));
        RRLR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRLR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRLR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RRLR);
        RRLR.setBounds(410, 360, 40, 30);

        RRLL.setBackground(new java.awt.Color(0, 126, 167));
        RRLL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRLL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRLL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RRLL);
        RRLL.setBounds(330, 360, 40, 30);

        RRRL.setBackground(new java.awt.Color(0, 126, 167));
        RRRL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RRRL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RRRL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        RRRL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRRLActionPerformed(evt);
            }
        });
        jPanel1.add(RRRL);
        RRRL.setBounds(490, 360, 40, 30);

        jPanel3.setBackground(new java.awt.Color(154, 209, 212));
        jPanel3.setLayout(null);

        T15.setEditable(false);
        T15.setBackground(new java.awt.Color(154, 209, 212));
        T15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T15);
        T15.setBounds(570, 10, 30, 40);

        T1.setEditable(false);
        T1.setBackground(new java.awt.Color(154, 209, 212));
        T1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T1);
        T1.setBounds(10, 10, 30, 40);

        T2.setEditable(false);
        T2.setBackground(new java.awt.Color(154, 209, 212));
        T2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T2);
        T2.setBounds(50, 10, 30, 40);

        T3.setEditable(false);
        T3.setBackground(new java.awt.Color(154, 209, 212));
        T3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T3);
        T3.setBounds(90, 10, 30, 40);

        T4.setEditable(false);
        T4.setBackground(new java.awt.Color(154, 209, 212));
        T4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T4);
        T4.setBounds(130, 10, 30, 40);

        T5.setEditable(false);
        T5.setBackground(new java.awt.Color(154, 209, 212));
        T5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T5);
        T5.setBounds(170, 10, 30, 40);

        T6.setEditable(false);
        T6.setBackground(new java.awt.Color(154, 209, 212));
        T6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T6);
        T6.setBounds(210, 10, 30, 40);

        T7.setEditable(false);
        T7.setBackground(new java.awt.Color(154, 209, 212));
        T7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T7);
        T7.setBounds(250, 10, 30, 40);

        T8.setEditable(false);
        T8.setBackground(new java.awt.Color(154, 209, 212));
        T8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        T8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T8ActionPerformed(evt);
            }
        });
        jPanel3.add(T8);
        T8.setBounds(290, 10, 30, 40);

        T9.setEditable(false);
        T9.setBackground(new java.awt.Color(154, 209, 212));
        T9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T9);
        T9.setBounds(330, 10, 30, 40);

        T10.setEditable(false);
        T10.setBackground(new java.awt.Color(154, 209, 212));
        T10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T10);
        T10.setBounds(370, 10, 30, 40);

        T11.setEditable(false);
        T11.setBackground(new java.awt.Color(154, 209, 212));
        T11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T11);
        T11.setBounds(410, 10, 30, 40);

        T12.setEditable(false);
        T12.setBackground(new java.awt.Color(154, 209, 212));
        T12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T12);
        T12.setBounds(450, 10, 30, 40);

        T13.setEditable(false);
        T13.setBackground(new java.awt.Color(154, 209, 212));
        T13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T13);
        T13.setBounds(490, 10, 30, 40);

        T14.setEditable(false);
        T14.setBackground(new java.awt.Color(154, 209, 212));
        T14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        T14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(T14);
        T14.setBounds(530, 10, 30, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 440, 710, 70);

        jButton5.setBackground(new java.awt.Color(154, 209, 212));
        jButton5.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 50, 73));
        jButton5.setText("Result");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 2, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(370, 520, 120, 50);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 50, 73));
        jLabel1.setText("Tree");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 0, 90, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/Untitled design (24).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 110, 620, 1040);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-macos-close-24.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(920, 0, 24, 30);

        jButton1.setBackground(new java.awt.Color(154, 209, 212));
        jButton1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Preorder");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 3, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 300, 130, 40);

        jButton3.setBackground(new java.awt.Color(154, 209, 212));
        jButton3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Inorder");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 3, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(750, 240, 130, 40);

        jButton4.setBackground(new java.awt.Color(154, 209, 212));
        jButton4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Postorder");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 73), 3, true));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(750, 360, 130, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-about-30.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 10, 30, 30);

        jLabel10.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 90, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/icons8-about-24.png"))); // NOI18N
        jLabel10.setText("How To Use?");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(760, 170, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void T8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T8ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
    //  jButton1.setForeground(Color.white);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
     // jButton1.setForeground(new Color(0,50,73));   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   i=0;
        for(int i=0;i<15;i++)
{ T.get(i).setText("");
    io.get(i).setForeground(Color.BLACK);}
        s.clear();o.clear();t.clear();ot.clear();
        jButton1.setForeground(new Color(0,50,73));
        jButton4.setForeground(new Color(102,102,102));
        jButton3.setForeground(new Color(102,102,102));
Preorder(tr.root);
while(!s.isEmpty())
{t.push(s.pop());
ot.push(o.pop());
}    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
for(int i=0;i<15;i++)
    io.get(i).setEditable(false);
jButton1.setEnabled(true);
jButton3.setEnabled(true);
jButton4.setEnabled(true);
tr.root=new Node(Integer.parseInt(R.getText()));

//LEFT SUBTREE

if("".equals(RL.getText()))
    tr.root.left=null;
else
{tr.root.left=new Node(Integer.parseInt(RL.getText()));n++;
if("".equals(RLL.getText()))
    tr.root.left.left=null;
else
{
    tr.root.left.left=new Node(Integer.parseInt(RLL.getText()));n++;
    if("".equals(RLLL.getText()))
        tr.root.left.left.left=null;
    else
    { tr.root.left.left.left=new Node(Integer.parseInt(RLLL.getText()));n++;}
    if("".equals(RLLR.getText()))
        tr.root.left.left.right=null;
    else
    {  tr.root.left.left.right=new Node(Integer.parseInt(RLLR.getText()));n++;}
}
if("".equals(RLR.getText()))
    tr.root.left.right=null;
else
{
    tr.root.left.right=new Node(Integer.parseInt(RLR.getText()));n++;
    if("".equals(RLRL.getText()))
        tr.root.left.right.left=null;
    else
    { tr.root.left.right.left=new Node(Integer.parseInt(RLRL.getText()));n++;}
    if("".equals(RLRR.getText()))
        tr.root.left.right.right=null;
    else
    {tr.root.left.right.right=new Node(Integer.parseInt(RLRR.getText()));n++;}
}    
}

//RIGHT SUBTREE

if("".equals(RR.getText()))
    tr.root.right=null;
else
{
    tr.root.right=new Node(Integer.parseInt(RR.getText()));n++;
    if("".equals(RRL.getText()))
        tr.root.right.left=null;
    else
    {  
        tr.root.right.left=new Node(Integer.parseInt(RRL.getText()));n++;
        if("".equals(RRLL.getText()))
            tr.root.right.left.left=null;
        else
        { tr.root.right.left.left=new Node(Integer.parseInt(RRLL.getText()));n++;}
        if("".equals(RRLR.getText()))
            tr.root.right.left.right=null;
        else
        { tr.root.right.left.right=new Node(Integer.parseInt(RRLR.getText()));n++;}
    
    }
    if("".equals(RRR.getText()))
        tr.root.right.right=null;
    else
    {
        tr.root.right.right=new Node(Integer.parseInt(RRR.getText()));n++;
        if("".equals(RRRL.getText()))
            tr.root.right.right.left=null;
        else
        {  tr.root.right.right.left=new Node(Integer.parseInt(RRRL.getText()));n++;}
        if("".equals(RRRR.getText()))
            tr.root.right.right.right=null;
        else
        {   tr.root.right.right.right=new Node(Integer.parseInt(RRRR.getText()));n++;}
    }
}



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
//jButton3.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
//jButton3.setForeground(new Color(0,50,73));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
    //jButton4.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
    //jButton4.setForeground(new Color(0,50,73));     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
i=0;
        for(int i=0;i<15;i++)
{ T.get(i).setText("");
    io.get(i).setForeground(Color.BLACK);}
s.clear();o.clear();t.clear();ot.clear();
        jButton4.setForeground(new Color(0,50,73));
        jButton1.setForeground(new Color(102,102,102));
        jButton3.setForeground(new Color(102,102,102));
Postorder(tr.root);
while(!s.isEmpty())
{t.push(s.pop());
ot.push(o.pop());
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(!t.isEmpty())
{T.get(i).setText(""+t.pop());
io.get(Integer.parseInt(""+ot.pop())).setForeground(Color.white);
i++;}
else
    JOptionPane.showMessageDialog(null,"Done");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
i=0;
        for(int i=0;i<15;i++)
{ T.get(i).setText("");
    io.get(i).setForeground(Color.BLACK);}
        s.clear();o.clear();t.clear();ot.clear();
        jButton3.setForeground(new Color(0,50,73));
        jButton1.setForeground(new Color(102,102,102));
        jButton4.setForeground(new Color(102,102,102));
        Inorder(tr.root); 
while(!s.isEmpty())
{t.push(s.pop());
ot.push(o.pop());
}
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
abouttree a=new abouttree();

a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
treeop a=new treeop();
a.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void RRRLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RRRLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RRRLActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
JOptionPane.showMessageDialog(null,"Enter unique elements in the tree then press on the \"Enter\" Key");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
jLabel10.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
jLabel10.setForeground(new Color(0,90,255)) ;       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(treeop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(treeop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(treeop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(treeop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new treeop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField R;
    private javax.swing.JTextField RL;
    private javax.swing.JTextField RLL;
    private javax.swing.JTextField RLLL;
    private javax.swing.JTextField RLLR;
    private javax.swing.JTextField RLR;
    private javax.swing.JTextField RLRL;
    private javax.swing.JTextField RLRR;
    private javax.swing.JTextField RR;
    private javax.swing.JTextField RRL;
    private javax.swing.JTextField RRLL;
    private javax.swing.JTextField RRLR;
    private javax.swing.JTextField RRR;
    private javax.swing.JTextField RRRL;
    private javax.swing.JTextField RRRR;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T12;
    private javax.swing.JTextField T13;
    private javax.swing.JTextField T14;
    private javax.swing.JTextField T15;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
